webtalk_init -webtalk_dir C:\\hdl_projects\\mb_linux\\mb_linux.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-04-21 20:04:35" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "176032993_1777485347_210642998_121" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8pt6p0nk1c9rllc288r28crtnn" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.036 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1555850096382" -context "sdk\\\\application/1555850096382"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1555850096382"
webtalk_add_data -client sdk -key apptemplate -value "linux_hello_world" -context "sdk\\\\application/1555850096382"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1555850096382"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1555850096382"
webtalk_add_data -client sdk -key Procused -value "" -context "sdk\\\\application/1555850096382"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1555873475293"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1555873475293"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1555873475293"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1555873475293"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1555873475293"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1555873475293"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1555873475293"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1555873475293"
webtalk_transmit -clientid 1622708824 -regid "176032993_1777485347_210642998_121" -xml C:\\hdl_projects\\mb_linux\\mb_linux.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\hdl_projects\\mb_linux\\mb_linux.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\hdl_projects\\mb_linux\\mb_linux.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
